#!/usr/bin/env fish
set primary (xgetres dmenu.color1)
set fg (xgetres dmenu.color7)
set bg (xgetres dmenu.color0)

switch $argv
case "to"
    set input (echo "" | dmenu -fn "FuraCode Nerd Font 12" -nb "$bg" -nf "$primary" -sb "$primary" -sf "$bg" -p "esperanto:")
    set translated (trans -b en:eo "$input")
    set lower (string lower "$translated")
    xdotool type "$lower"
case "from"
    set input (xclip -selection clipboard -o)
    set translated (trans -b :en "$input")
    set lower (string lower "$translated")
    echo "$lower"
    echo "$lower" | xclip -selection clipboard -i
end
