#!/usr/bin/env fish
set img $argv
aplay $HOME/.screenie/capture.wav &
set url (sharenix -q -m="f" $img)
aplay $HOME/.screenie/complete.wav &
echo -n "$url" | xclip -selection "clipboard"
notify-send -i "$HOME/.screenie/sharex.png" "File Uploaded" "$url"
